apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service-deployment
  labels:
    app: movie-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
      - name: movie-service
        image: 77771603/movie-service:latest
        ports:
        - containerPort: 6000
        env:
          - name: DB_HOST
            value: "movies-db"
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            value: "postgres"
          - name: DB_PASSWORD
            value: "postgres"
          - name: DB_NAME
            value: "movies_db"
          - name: JWT_SECRET
            value: "superSecret"
          - name: MOVIES_PORT
            value: "6000"
