services:
  ################################################################
  # 1. POSTGRES
  ################################################################
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase

    ports:
      - "5432:5432" # Pour exposer Postgres en local si besoin
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  ################################################################
  # 2. AUTH-SERVICE
  ################################################################
  auth-service:
    build:
      context: ./auth-service
      # dockerfile: Dockerfile  # (par défaut "Dockerfile")
    container_name: auth-service
    # on monte le port local 5000 => conteneur 5000
    ports:
      - "5000:5000"
    env_file:
      - ./auth-service/.env.dev
    # On peut forcer/écraser des variables ci-dessous si on veut :
    # environment:
    #   DATABASE_URL: "postgres://myuser:mypassword@postgres:5432/authdb"
    depends_on:
      - postgres

  ################################################################
  # 3. BOOK-SERVICE
  ################################################################
  book-service:
    build:
      context: ./book-service
    container_name: book-service
    ports:
      - "5001:5001"
    env_file:
      - ./book-service/.env.dev
    # environment:
    #   DATABASE_URL: "postgres://myuser:mypassword@postgres:5432/bookdb"
    depends_on:
      - auth-service
      - postgres

volumes:
  pgdata:
