services:
  # ====================================================
  # Auth Service
  # ====================================================
  auth-db:
    image: postgres:latest
    container_name: auth-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432" # exposé en local sur le port 5433

  auth-service:
    build: ./auth-service
    container_name: auth-service
    environment:
      DB_HOST: auth-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: auth_db
      AUTH_PORT: 4000
      JWT_SECRET: superSecret
    ports:
      - "4000:3000"   # côté host :4000 -> côté conteneur :3000
    depends_on:
      - auth-db

  # ====================================================
  # Books Service
  # ====================================================
  books-db:
    image: postgres:latest
    container_name: books-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books_db
    ports:
      - "5434:5432"

  books-service:
    build: ./book-service
    container_name: books-service
    environment:
      DB_HOST: books-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: books_db
      BOOKS_PORT: 5000
      JWT_SECRET: superSecret
    ports:
      - "5000:3001"
    depends_on:
      - books-db

  # ====================================================
  # Movies Service
  # ====================================================
  movies-db:
    image: postgres:latest
    container_name: movies-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movies_db
    ports:
      - "5435:5432"

  movies-service:
    build: ./movie-service
    container_name: movies-service
    environment:
      DB_HOST: movies-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: movies_db
      MOVIES_PORT: 6000
      JWT_SECRET: superSecret
    ports:
      - "6000:6000"
    depends_on:
      - movies-db


