apiVersion: apps/v1
kind: Deployment
metadata:
  name: book
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
        - name: book-service
          image: book-service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              value: "postgres://myuser:mypassword@postgres:5432/book-db?schema=public"
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: book
spec:
  ports:
    - port: 3001
  selector:
    app: book-service
