apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
data:
  init.sql: |
    -- Create databases
    CREATE DATABASE "auth-db";
    CREATE DATABASE "book-db";

    -- Grant privileges to the superuser (myuser)
    GRANT ALL PRIVILEGES ON DATABASE "auth-db" TO myuser;
    GRANT ALL PRIVILEGES ON DATABASE "book-db" TO myuser;