name: Book Service Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  book-tests:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.ACTION_SECRET_KEY }}
      REFRESH_SECRET_KEY: ${{ secrets.ACTION_REFRESH_SECRET_KEY }}

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: book-db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # -----------------------------------------
      # 1. Install + Start Auth Service
      # -----------------------------------------
      - name: Install & Start Auth Service
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/auth-db
          NODE_ENV: development 
        run: |
          cd auth-service
          npm install

          # Explicitly generate Prisma client
          npx prisma generate --schema=src/prisma/schema.prisma --output=./node_modules/.prisma/client

          # Run migrations
          npx prisma migrate deploy --name init --schema=src/prisma/schema.prisma

          # Start server in background and capture PID
          node server.js > auth-service.log 2>&1 &
          echo $! > auth-service.pid

          # Wait for Auth Service to become available
          for i in {1..10}; do
            if curl -s http://localhost:5000/health; then
              echo "✅ Auth Service is up!"
              break
            fi
            cat auth-service.log

            echo "🚀 Waiting for Auth Service..."
            sleep 3
          done
          cd ..

      # -----------------------------------------
      # 2. Setup & Prepare Book Service
      # -----------------------------------------
      - name: Install Dependencies
        run: npm install
        working-directory: book-service

      - name: Install Prisma Client
        run: npm install @prisma/client
        working-directory: book-service

      - name: Generate Prisma Client
        run: npx prisma generate --output=./node_modules/.prisma/client
        working-directory: book-service

      - name: Apply Database Migrations
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/book-db
        run: npx prisma migrate deploy
        working-directory: book-service

      # -----------------------------------------
      # 3. Run Tests
      # -----------------------------------------
      - name: Run Tests
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/book-db
          AUTH_SERVICE_URL: http://localhost:5000/api/auth
        run: npm test
        working-directory: book-service
