name: Book Service Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  book-tests:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.ACTION_SECRET_KEY }}
      REFRESH_SECRET_KEY: ${{ secrets.ACTION_REFRESH_SECRET_KEY }}

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: bookdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # -----------------------------------------
      # 1. Install + Start Auth Service
      # -----------------------------------------
      - name: Install & Start Auth Service
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/auth-db
        run: |
          cd auth-service
          npm install

          # Explicitly generate Prisma client
          npx prisma generate --schema=src/prisma/schema.prisma

          # Run migrations
          npx prisma migrate dev --name init --schema=src/prisma/schema.prisma

          # Start server with proper NODE_ENV
          NODE_ENV=production PORT=5000 node server.js &

          # Wait for auth service
          curl --retry 10 --retry-delay 3 --retry-connrefused http://localhost:5000/health
          echo "✅ Auth Service ready"
          cd ..

      # -----------------------------------------
      # 2. Setup & Prepare Book Service
      # -----------------------------------------
      - name: Install Dependencies
        run: npm install
        working-directory: book-service

      - name: Install Prisma Client
        run: npm install @prisma/client
        working-directory: book-service

      - name: Generate Prisma Client
        run: npx prisma generate
        working-directory: book-service

      - name: Apply Database Migrations
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/bookdb
        run: npx prisma migrate deploy
        working-directory: book-service

      # -----------------------------------------
      # 3. Run Tests
      # -----------------------------------------
      - name: Run Tests
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/bookdb
          AUTH_SERVICE_URL: http://localhost:5000/api/auth
        run: npm test
        working-directory: book-service
