name: Book Service Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  book-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: book-service
        run: npm install

      - name: Run tests
        working-directory: book-service
        run: npm test
